[project]
name = ""
version = ""
description = ""
authors = [
    {name = "fathurifki", email = "rifkifathu@gmail.com"},
]
dependencies = [
    "django>=5.0.6",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

